require Rails.root.join('db', 'dev_seeds', 'religions.rb')
require Rails.root.join('db', 'dev_seeds', 'castes.rb')
require Rails.root.join('db', 'dev_seeds', 'education_levels.rb')
require Rails.root.join('db', 'dev_seeds', 'professions.rb')
# require Rails.root.join('db', 'dev_seeds', 'country_state.rb')
# require Rails.root.join('db', 'dev_seeds', 'districts.rb')
# require Rails.root.join('db', 'dev_seeds', 'constituencies.rb')
require Rails.root.join('db', 'dev_seeds', 'issue_categories.rb')
# require Rails.root.join('db', 'dev_seeds', 'elections.rb')
# require Rails.root.join('db', 'dev_seeds', 'parties.rb')
# require Rails.root.join('db', 'dev_seeds', 'users.rb')
# require Rails.root.join('db', 'dev_seeds', 'candidates.rb')
# require Rails.root.join('db', 'dev_seeds', 'user_posts.rb')
# require Rails.root.join('db', 'dev_seeds', 'candidatures.rb')
