image: "ruby:2.4"
services:
  # - postgres:9.6
  - mdillon/postgis:9.6
variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  DATABASE_URL: "postgis://runner:@mdillon-postgis/test_db"
before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
  - cp config/database.yml.gitlab config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:gis:setup db:schema:load
rspec:
  script:
    - RAILS_ENV=test bundle exec rspec --format documentation
heroku_dev_deploy:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --api-key=$HEROKU_DEV_API_KEY --app=$HEROKU_DEV_APP
  only:
  - develop
heroku_production_deploy:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --api-key=$HEROKU_PRODUCTION_API_KEY --app=$HEROKU_PRODUCTION_APP
  only:
  - master
